#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "silverbullet"
name = "SilverBullet"
description.en = "Creative space where you collect, create and expand your personal knowledge"
description.fr = "Espace créatif où vous recueillez, créez et élargissez vos connaissances personnelles"

version = "2.6.1~ynh1"

maintainers = ["fflorent"]

[upstream]
license = "MIT"
website = "https://silverbullet.md"
code = "https://github.com/silverbulletmd/silverbullet"
fund = "https://silverbullet.md/Funding"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = true

ldap = false
sso = false

disk = "100M"
ram.build = "50M"
ram.runtime = "250M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    help.en = "Choose the user who can access to silverbullet"
    help.fr = "Choisissez l'utilisateur pouvant accéder à silverbullet"
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir=false

    amd64.url = "https://github.com/silverbulletmd/silverbullet/releases/download/2.6.1/silverbullet-server-linux-x86_64.zip"
    amd64.sha256 = "74b8bc47dad51694ff2450a823af453e5750db5a12de02f60d32802b90f131d7"
    arm64.url = "https://github.com/silverbulletmd/silverbullet/releases/download/2.6.1/silverbullet-server-linux-aarch64.zip"
    arm64.sha256 = "05a9e8740957a5d253888b7b1d975c308738165946bc5d098e3f50ccae26f161"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^silverbullet-server-linux-x86_64.zip$"
    autoupdate.asset.arm64 = "^silverbullet-server-linux-aarch64.zip$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "notes" ]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    [resources.ports]
    main.default = 3000
