#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors


run__v1_domain() {
    ynh_print_info "Running 'my_action'..."
}

ynh_app_config_run "$1"
