#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    ynh_script_progression "Removing $app service integration..."
    yunohost service remove "$app"
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

# Remove other various files specific to the app... such as :

ynh_safe_rm "$data_dir/custom.env"
ynh_safe_rm "$install_dir/default.env"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
